export const Users = [
    {
      id:1,
      profilePicture: "assets/person/Naruto.jpg",
      username: "Uzumaki Naruto",
    },
    {
      id:2,
      profilePicture: "assets/person/Aang.jpg",
      username: "Aang",
    },
    {
      id:3,
      profilePicture: "assets/person/Ben.png",
      username: "Ben Tennyson",
    },
    {
      id:4,
      profilePicture: "assets/person/Gara.jpg",
      username: "Gara",
    },
    {
      id:5,
      profilePicture: "assets/person/Goku.jpg",
      username: "Goku",
    },
    {
      id:6,
      profilePicture: "assets/person/ironman.jpg",
      username: "Stark",
    },
    {
      id:7,
      profilePicture: "assets/person/Pikachu.jpg",
      username: "Aash Kechum",
    },
    {
      id:8,
      profilePicture: "assets/person/Itachi.jpg",
      username: "Uchhiha Itachi",
    },
    {
      id:9,
      profilePicture: "assets/person/sasuke.jpg",
      username: "Uchhiha Sasuke",
    },
    {
      id:10,
      profilePicture: "assets/person/Thanos.jpg",
      username: "Thanos",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "assets/person/Naruto.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "assets/person/Aang.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "assets/person/Ben.png",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "assets/person/Gara.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "assets/person/Goku.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "assets/person/ironman.jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "assets/person/Pikachu.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "assets/person/Itachi.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "assets/person/sasuke.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "assets/person/Thanos.jpg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];